# Generated by Django 5.0 on 2025-10-21 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_datos_capturados', models.IntegerField(default=0)),
                ('inclinacion_promedio', models.FloatField(blank=True, help_text='Ángulo promedio (°)', null=True)),
                ('fuerza_promedio', models.FloatField(blank=True, help_text='Fuerza promedio (g)', null=True)),
                ('fuerza_maxima', models.FloatField(blank=True, help_text='Fuerza máxima (g)', null=True)),
                ('calificacion', models.FloatField(blank=True, help_text='Calificación de 0.0 a 5.0', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('tecnica_correcta', models.BooleanField(default=False)),
                ('angulo_adecuado', models.BooleanField(default=False)),
                ('presion_controlada', models.BooleanField(default=False)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('practica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumen', to='placa.practicaactiva')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_evaluadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resumen de Práctica',
                'verbose_name_plural': 'Resúmenes de Prácticas',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
    ]
