# Generated by Django 5.0 on 2025-11-26 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('placa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilidad_uso', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='¿Qué tan fácil fue usar el sistema? (1=Muy difícil, 5=Muy fácil)')),
                ('utilidad_sistema', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='¿Qué tan útil fue el sistema para tu práctica? (1=Nada útil, 5=Muy útil)')),
                ('precision_sensores', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='¿Qué tan precisos consideras los sensores? (1=Nada precisos, 5=Muy precisos)')),
                ('interfaz_clara', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='¿Qué tan clara fue la interfaz? (1=Muy confusa, 5=Muy clara)')),
                ('mejora_aprendizaje', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='¿El sistema mejoró tu aprendizaje? (1=Nada, 5=Mucho)')),
                ('aspectos_positivos', models.TextField(blank=True, help_text='¿Qué te gustó del sistema?')),
                ('aspectos_negativos', models.TextField(blank=True, help_text='¿Qué no te gustó del sistema?')),
                ('sugerencias', models.TextField(blank=True, help_text='Sugerencias de mejora')),
                ('recomendaria', models.BooleanField(default=True, help_text='¿Recomendarías este sistema?')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='estudiantes.estudiante')),
                ('practica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='placa.practicaactiva')),
            ],
            options={
                'verbose_name': 'Encuesta del Sistema',
                'verbose_name_plural': 'Encuestas del Sistema',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='ReporteGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Reporte de Desempeño', max_length=200)),
                ('fecha_inicio', models.DateTimeField(help_text='Inicio del período del reporte')),
                ('fecha_fin', models.DateTimeField(help_text='Fin del período del reporte')),
                ('total_estudiantes', models.IntegerField(default=0)),
                ('total_practicas', models.IntegerField(default=0)),
                ('total_datos_capturados', models.IntegerField(default=0)),
                ('promedio_precision', models.FloatField(default=0.0, help_text='Precisión promedio general (%)')),
                ('promedio_intentos', models.FloatField(default=0.0, help_text='Promedio de intentos por estudiante')),
                ('promedio_tiempo', models.FloatField(default=0.0, help_text='Tiempo promedio de práctica (minutos)')),
                ('promedio_calificacion', models.FloatField(default=0.0, help_text='Calificación promedio')),
                ('promedio_satisfaccion', models.FloatField(default=0.0, help_text='Satisfacción promedio (1-5)')),
                ('total_encuestas', models.IntegerField(default=0)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_generados', to='profesor.profesor')),
            ],
            options={
                'verbose_name': 'Reporte General',
                'verbose_name_plural': 'Reportes Generales',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='ResumenPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_datos_capturados', models.IntegerField(default=0)),
                ('inclinacion_promedio', models.FloatField(blank=True, help_text='Ángulo promedio (°)', null=True)),
                ('fuerza_promedio', models.FloatField(blank=True, help_text='Fuerza promedio (g)', null=True)),
                ('fuerza_maxima', models.FloatField(blank=True, help_text='Fuerza máxima (g)', null=True)),
                ('fuerza_minima', models.FloatField(blank=True, help_text='Fuerza mínima (g)', null=True)),
                ('numero_intentos', models.IntegerField(default=0, help_text='Total de intentos realizados')),
                ('intentos_exitosos', models.IntegerField(default=0, help_text='Intentos con técnica correcta')),
                ('precision_porcentaje', models.FloatField(default=0.0, help_text='Precisión general (%)')),
                ('tiempo_canalizacion', models.IntegerField(default=0, help_text='Tiempo total de canalización (segundos)')),
                ('calificacion', models.FloatField(blank=True, help_text='Calificación de 0.0 a 5.0', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('tecnica_correcta', models.BooleanField(default=False)),
                ('angulo_adecuado', models.BooleanField(default=False)),
                ('presion_controlada', models.BooleanField(default=False)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('practica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumen', to='placa.practicaactiva')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_evaluadas', to='profesor.profesor')),
            ],
            options={
                'verbose_name': 'Resumen de Práctica',
                'verbose_name_plural': 'Resúmenes de Prácticas',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
    ]
