# Generated by Django 5.0 on 2025-11-14 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('placa', '0002_datossensor_tecnica_correcta_and_more'),
        ('profesor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resumenpractica',
            name='fuerza_minima',
            field=models.FloatField(blank=True, help_text='Fuerza mínima (g)', null=True),
        ),
        migrations.AddField(
            model_name='resumenpractica',
            name='intentos_exitosos',
            field=models.IntegerField(default=0, help_text='Intentos con técnica correcta'),
        ),
        migrations.AddField(
            model_name='resumenpractica',
            name='numero_intentos',
            field=models.IntegerField(default=0, help_text='Total de intentos realizados'),
        ),
        migrations.AddField(
            model_name='resumenpractica',
            name='precision_porcentaje',
            field=models.FloatField(default=0.0, help_text='Precisión general (%)'),
        ),
        migrations.AddField(
            model_name='resumenpractica',
            name='tiempo_canalizacion',
            field=models.IntegerField(default=0, help_text='Tiempo total de canalización (segundos)'),
        ),
        migrations.CreateModel(
            name='EncuestaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilidad_uso', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='¿Qué tan fácil fue usar el sistema? (1=Muy difícil, 5=Muy fácil)')),
                ('utilidad_sistema', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='¿Qué tan útil fue el sistema para tu práctica? (1=Nada útil, 5=Muy útil)')),
                ('precision_sensores', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='¿Qué tan precisos consideras los sensores? (1=Nada precisos, 5=Muy precisos)')),
                ('interfaz_clara', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='¿Qué tan clara fue la interfaz? (1=Muy confusa, 5=Muy clara)')),
                ('mejora_aprendizaje', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='¿El sistema mejoró tu aprendizaje? (1=Nada, 5=Mucho)')),
                ('aspectos_positivos', models.TextField(blank=True, help_text='¿Qué te gustó del sistema?')),
                ('aspectos_negativos', models.TextField(blank=True, help_text='¿Qué no te gustó del sistema?')),
                ('sugerencias', models.TextField(blank=True, help_text='Sugerencias de mejora')),
                ('recomendaria', models.BooleanField(default=True, help_text='¿Recomendarías este sistema?')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='estudiantes.estudiante')),
                ('practica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='placa.practicaactiva')),
            ],
            options={
                'verbose_name': 'Encuesta del Sistema',
                'verbose_name_plural': 'Encuestas del Sistema',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.CreateModel(
            name='ReporteGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Reporte de Desempeño', max_length=200)),
                ('fecha_inicio', models.DateTimeField(help_text='Inicio del período del reporte')),
                ('fecha_fin', models.DateTimeField(help_text='Fin del período del reporte')),
                ('total_estudiantes', models.IntegerField(default=0)),
                ('total_practicas', models.IntegerField(default=0)),
                ('total_datos_capturados', models.IntegerField(default=0)),
                ('promedio_precision', models.FloatField(default=0.0, help_text='Precisión promedio general (%)')),
                ('promedio_intentos', models.FloatField(default=0.0, help_text='Promedio de intentos por estudiante')),
                ('promedio_tiempo', models.FloatField(default=0.0, help_text='Tiempo promedio de práctica (minutos)')),
                ('promedio_calificacion', models.FloatField(default=0.0, help_text='Calificación promedio')),
                ('promedio_satisfaccion', models.FloatField(default=0.0, help_text='Satisfacción promedio (1-5)')),
                ('total_encuestas', models.IntegerField(default=0)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte General',
                'verbose_name_plural': 'Reportes Generales',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
