# Generated by Django 5.0 on 2025-11-26 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('profesor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='profesor',
            field=models.ForeignKey(blank=True, help_text='Profesor asignado a este estudiante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='profesor.profesor'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL),
        ),
    ]
