# Generated by Django 5.0 on 2025-11-20 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('placa', '0002_datossensor_tecnica_correcta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_angulo_correcto', models.CharField(default='#00FF00', help_text='Color hex para ángulos correctos', max_length=7)),
                ('color_angulo_incorrecto', models.CharField(default='#FF0000', help_text='Color hex para ángulos incorrectos', max_length=7)),
                ('color_fuerza_correcta', models.CharField(default='#0000FF', help_text='Color hex para fuerza correcta', max_length=7)),
                ('mostrar_grid', models.BooleanField(default=True, help_text='Mostrar grilla de referencia')),
                ('mostrar_angulos', models.BooleanField(default=True, help_text='Mostrar valores de ángulos')),
                ('mostrar_fuerza', models.BooleanField(default=True, help_text='Mostrar valores de fuerza')),
                ('mostrar_historial', models.BooleanField(default=True, help_text='Mostrar gráfico de historial')),
                ('audio_feedback', models.BooleanField(default=True, help_text='Activar feedback de audio')),
                ('volumen', models.FloatField(default=0.5, help_text='Volumen de 0.0 a 1.0')),
                ('fps_objetivo', models.IntegerField(default=30, help_text='FPS objetivo para actualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_ra', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Configuración RA',
                'verbose_name_plural': 'Configuraciones RA',
            },
        ),
        migrations.CreateModel(
            name='SesionRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo_ra', models.CharField(help_text='Tipo de dispositivo RA (HoloLens, Meta Quest, etc.)', max_length=100)),
                ('estado', models.CharField(choices=[('conectando', 'Conectando'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('desconectada', 'Desconectada'), ('error', 'Error')], default='conectando', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('modo_visualizacion', models.CharField(default='overlay', help_text='Modo de visualización: overlay, hologram, mixed', max_length=50)),
                ('escala_modelo', models.FloatField(default=1.0, help_text='Escala del modelo 3D')),
                ('opacidad', models.FloatField(default=0.8, help_text='Opacidad de 0.0 a 1.0')),
                ('total_datos_recibidos', models.IntegerField(default=0)),
                ('latencia_promedio', models.FloatField(default=0.0, help_text='Latencia promedio en ms')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_ra', to='estudiantes.estudiante')),
                ('practica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_ra', to='placa.practicaactiva')),
            ],
            options={
                'verbose_name': 'Sesión RA',
                'verbose_name_plural': 'Sesiones RA',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EventoRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('conexion', 'Conexión Establecida'), ('desconexion', 'Desconexión'), ('error', 'Error'), ('cambio_config', 'Cambio de Configuración'), ('inicio_practica', 'Inicio de Práctica'), ('fin_practica', 'Fin de Práctica'), ('calibracion', 'Calibración')], max_length=20)),
                ('descripcion', models.TextField()),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='RA.sesionra')),
            ],
            options={
                'verbose_name': 'Evento RA',
                'verbose_name_plural': 'Eventos RA',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DatosVisualizacionRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_envio', models.DateTimeField(auto_now_add=True)),
                ('timestamp_recepcion', models.DateTimeField(blank=True, null=True)),
                ('latencia_ms', models.FloatField(blank=True, help_text='Latencia en milisegundos', null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('error_entrega', models.TextField(blank=True)),
                ('dato_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones_ra', to='placa.datossensor')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_visualizacion', to='RA.sesionra')),
            ],
            options={
                'verbose_name': 'Dato de Visualización RA',
                'verbose_name_plural': 'Datos de Visualización RA',
                'ordering': ['-timestamp_envio'],
                'indexes': [models.Index(fields=['sesion', '-timestamp_envio'], name='RA_datosvis_sesion__2d3cc4_idx')],
            },
        ),
    ]
