# Generated by Django 5.0 on 2025-11-26 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RA', '0001_initial'),
        ('estudiantes', '0001_initial'),
        ('placa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionra',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_ra', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='datosvisualizacionra',
            name='dato_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones_ra', to='placa.datossensor'),
        ),
        migrations.AddField(
            model_name='sesionra',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_ra', to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='sesionra',
            name='practica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_ra', to='placa.practicaactiva'),
        ),
        migrations.AddField(
            model_name='eventora',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='RA.sesionra'),
        ),
        migrations.AddField(
            model_name='datosvisualizacionra',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_visualizacion', to='RA.sesionra'),
        ),
        migrations.AddIndex(
            model_name='datosvisualizacionra',
            index=models.Index(fields=['sesion', '-timestamp_envio'], name='RA_datosvis_sesion__2d3cc4_idx'),
        ),
    ]
