# Generated by Django 5.0 on 2025-10-21 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoESP32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='VeinView Device', max_length=100)),
                ('mac_address', models.CharField(help_text='Formato: XX:XX:XX:XX:XX:XX', max_length=17, unique=True)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dispositivo ESP32',
                'verbose_name_plural': 'Dispositivos ESP32',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='PracticaActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='iniciada', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_pausa', models.DateTimeField(blank=True, null=True)),
                ('fecha_reanudacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_total_segundos', models.IntegerField(default=0, help_text='Duración acumulada en segundos')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='placa.dispositivoesp32')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Práctica Activa',
                'verbose_name_plural': 'Prácticas Activas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DatosSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceleracion_x', models.FloatField(help_text='Aceleración eje X (m/s²)')),
                ('aceleracion_y', models.FloatField(help_text='Aceleración eje Y (m/s²)')),
                ('aceleracion_z', models.FloatField(help_text='Aceleración eje Z (m/s²)')),
                ('giroscopio_x', models.FloatField(help_text='Giroscopio eje X (°/s)')),
                ('giroscopio_y', models.FloatField(help_text='Giroscopio eje Y (°/s)')),
                ('giroscopio_z', models.FloatField(help_text='Giroscopio eje Z (°/s)')),
                ('angulo_pitch', models.FloatField(help_text='Ángulo de inclinación pitch (°)')),
                ('angulo_roll', models.FloatField(help_text='Ángulo de inclinación roll (°)')),
                ('angulo_yaw', models.FloatField(help_text='Ángulo de inclinación yaw (°)')),
                ('fuerza', models.FloatField(help_text='Fuerza aplicada (gramos)')),
                ('presion', models.FloatField(blank=True, help_text='Presión calculada (N/cm²)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='placa.dispositivoesp32')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_sensores', to='placa.practicaactiva')),
            ],
            options={
                'verbose_name': 'Dato de Sensor',
                'verbose_name_plural': 'Datos de Sensores',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['practica', '-timestamp'], name='placa_datos_practic_452b2d_idx'), models.Index(fields=['dispositivo', '-timestamp'], name='placa_datos_disposi_736a08_idx')],
            },
        ),
    ]
