# Generated by Django 5.0 on 2025-11-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datossensor',
            name='tecnica_correcta',
            field=models.BooleanField(default=False, help_text='¿Datos dentro de rango óptimo?'),
        ),
        migrations.AddField(
            model_name='practicaactiva',
            name='intentos_exitosos',
            field=models.IntegerField(default=0, help_text='Intentos con técnica correcta'),
        ),
        migrations.AddField(
            model_name='practicaactiva',
            name='numero_intentos',
            field=models.IntegerField(default=0, help_text='Número de intentos de canalización'),
        ),
        migrations.AddField(
            model_name='practicaactiva',
            name='precision_promedio',
            field=models.FloatField(default=0.0, help_text='Precisión promedio (%)'),
        ),
    ]
